import type { DryRunResult, PreflightResult, QueueItem } from '../../domain/models';
import { getTweetPreview } from '../../extraction/tweet-preview';
import { getUserFacingMessage } from '../services/error-messages';
import { formatTime, useI18n } from '../../i18n';

export function CurrentTweetCard({ item, position, logoUrl }: { item?: QueueItem; position?: number; logoUrl: string }) {
  const { t } = useI18n();
  return <section className="card current-card"><div className="current-heading"><div className="current-brand"><img src={logoUrl} alt="" /><div><span className="eyebrow">{t('operation.currentTweet')}</span><h2>{t('operation.currentTweet')}</h2></div></div>{item && <span className={`item-status status-${item.status}`}>{t(`statuses.${item.status}`)}</span>}</div>{item ? <><p className="current-preview" dir="auto">{getTweetPreview(item.targetUrl, item.label || t('common.unlabeledPost'), 180)}</p><div className="current-meta"><span>{t('ui.currentItem')} {position ?? item.position}</span><span>{t('common.attempts')} {item.attempts}</span>{item.startedAt && <span>{t('operation.started')} {formatTime(item.startedAt)}</span>}</div>{item.lastError && <p className="error-text">{t('operation.lastError')}: {getUserFacingMessage(item.lastError)}</p>}<a className="primary-link" href={item.targetUrl} target="_blank" rel="noreferrer">{t('common.openTweetLink')}</a></> : <p className="muted">{t('operation.noCurrentTweet')} {t('common.queue')} {t('operation.fromTab')} {t('nav.operation')}.</p>}</section>;
}

export function RecoveryCard({ logoUrl, failedCount, onResume, onStartOver, onCancel }: { logoUrl: string; failedCount: number; onResume: () => void; onStartOver: () => void; onCancel: () => void }) {
  const { t } = useI18n();
  return <section className="card recovery-card"><div className="current-brand"><img src={logoUrl} alt="" /><div><span className="eyebrow">X-PILOT</span><h2>{t('recovery.title')}</h2></div></div><p className="muted">{t('recovery.message')}</p><p className="recovery-hint muted">{t('recovery.startOverHint')}</p><div className="recovery-actions"><button className="primary" onClick={onResume}>{t('actions.resume')} {t('common.queue')}</button><button onClick={onStartOver}>{t('recovery.startOver')}{failedCount > 0 && <span className="recovery-count">{failedCount}</span>}</button><button className="danger" onClick={onCancel}>{t('recovery.cancelSession')}</button></div></section>;
}

export function PreflightCard({ result, onCheck }: { result: PreflightResult | null; onCheck: () => void }) {
  const { t } = useI18n();
  return <section className={`card preflight-card ${result ? (result.ready ? 'preflight-ready' : 'preflight-blocked') : ''}`}><div className="section-heading"><div><span className="eyebrow">{t('tests.preflight')}</span><h2>{t('tests.validation')}</h2></div><button className="primary" onClick={onCheck}>{t('tests.runPreflight')}</button></div>{result ? <><div className="preflight-summary"><strong>{t(result.summaryKey, result.summaryParams)}</strong><span>{result.counts.ready} {t('preflight.readyCount')} · {result.counts.published} {t('operation.published')} · {result.counts.duplicates + result.counts.publishedDuplicates} {t('diff.DUPLICATE')} · {result.counts.invalid} {t('preflight.invalid')}</span></div><div className="preflight-checks">{result.checks.map((check) => <div className={`preflight-check preflight-${check.status.toLowerCase()}`} key={check.id}><span className="preflight-icon" aria-hidden="true">{check.status === 'PASS' ? '✓' : check.status === 'WARN' ? '!' : '×'}</span><div><strong>{t(check.messageKey, check.params)}</strong>{check.detailsKey && <small>{t(check.detailsKey, check.params && typeof check.params.reason === 'string' ? { ...check.params, reason: getUserFacingMessage(check.params.reason) } : check.params)}</small>}</div></div>)}</div><small className="muted">{t('preflight.autoInspected')} · {t('preflight.lastCheck')}: {formatTime(result.checkedAt)}</small></> : <p className="muted">{t('preflight.pressCheck')}</p>}</section>;
}

function getDryRunPreview(targetUrl: string, fallback: string): string {
  const text = getTweetPreview(targetUrl, undefined, 1000).trim();
  return text.split(/\s+/u).slice(0, 10).join(' ') || fallback;
}

export function DryRunCard({ result, onFirst, onQueue, onStop }: { result: DryRunResult | null; onFirst: () => void; onQueue: () => void; onStop: () => void }) {
  const { t } = useI18n();
  return <section className="card"><div className="section-heading"><div><span className="eyebrow">{t('tests.dryRun')}</span><h2>{t('tests.dryRunTitle')}</h2></div>{result && <span className={`item-status status-${result.status}`}>{t(`statuses.${result.status}`)}</span>}</div><p className="muted">{t('tests.noPost')}</p><div className="row controls-row"><button onClick={onFirst} disabled={result?.status === 'RUNNING'}>{t('tests.testFirst')}</button><button className="primary" onClick={onQueue} disabled={result?.status === 'RUNNING'}>{t('tests.testQueue')}</button><button className="danger" onClick={onStop} disabled={result?.status !== 'RUNNING'}>{t('tests.stopTest')}</button></div>{result && <><div className="stats"><div><b>{result.checked}</b><span>{t('tests.checked')}</span></div><div><b>{result.ready}</b><span>{t('preflight.readyCount')}</span></div><div><b>{result.failed}</b><span>{t('operation.failed')}</span></div><div><b>{result.total}</b><span>{t('tests.total')}</span></div></div>{result.status === 'FAILED' && result.error && <div className="runtime-warning" role="alert">{t('tests.startFailed')}: <b dir="auto">{getUserFacingMessage(result.error)}</b></div>}<div className="queue">{result.items.map((item) => <div className="queue-row" key={item.queueItemId}><strong>{t('tests.itemNumber', { position: item.position })}</strong><span className={`item-status status-${item.status}`}>{t(`statuses.${item.status}`)}</span><span className="dry-run-preview" dir="auto">{getDryRunPreview(item.targetUrl, t('tests.xPostReady'))}</span>{item.reason && <small>{getUserFacingMessage(item.reason)}</small>}</div>)}</div></>}</section>;
}
